---
title: Blogolicious test blog!
description: just another blog
# by default generate semi-random secret, change it to something if you want to run more than one instance !
secret: ~

tmp_dir:  tmp
repo_dir: examples/blog-bootstrap
# dir for comments that were marked for moderation.
# new posts will be put in "mod" and you shoudl move moderated ones to ham/spam dirs
# defailts to $repo_dir/mod
moderation_dir:
# can be more than one, in order of priority
# defaults to repo_dir/public
#static_paths:
#    - examples/blog/public
base_url: http://127.0.0.1:3000
rss_item_count: 30
posts_per_page: 10

default_layout: main

# debug: 1

backends:
    post:
        module: file
        cfg:
            dir: posts/

plugins:
    spam:
        spam_threshold: 0.6
        moderate_threshold: 0.4
        plugins:
            - plugin: spam
              config: {}
              weight: 1
            - plugin: random
              weight: 1



      # if you want to put it into production with hypnotoad, 2 x num_of_cores is good starting point
hypnotoad:
    workers: 8
