requires 'AnyEvent';
requires 'EV';
requires 'File::Slurp';
requires 'File::Slurp';
requires 'Module::Load';
requires 'Mojolicious', '>= 4.80';
requires 'Mojolicious::Plugin::TtRenderer';
requires 'Test::More';
requires 'Text::Markdown::Discount';
requires 'URI::Encode';
requires 'XML::Feed';
requires 'YAML::XS';
requires 'common::sense';
