#!/usr/bin/env perl
use lib '../lib';
use EV;
use AnyEvent;
# Start commands for application
     my $w = AnyEvent->timer (
      after    => 1,
      interval => 1,
      cb       => sub {print "Any Event working!!!\n";system("date >>/tmp/log");},
   );

use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec::Functions qw(catdir splitdir);


# Source directory has precedence
my @base = (splitdir(dirname(__FILE__)), '..');
my $lib = join('/', @base, 'lib');
-e catdir(@base, 't') ? unshift(@INC, $lib) : push(@INC, $lib);


require Mojolicious::Commands;
Mojolicious::Commands->start_app('Blogolicious');
