#!/bin/sh
DATE=$(date +%F)
FILENAME=${DATE}_$(perl -e 'print join("_",@ARGV)' $@);
TIMESTAMP=$(date +%FT%X%z)
cat <<EOF >$FILENAME
---
title: $@
date: $TIMESTAMP
author: $GIT_AUTHOR_NAME
category:
    -
tag:
    -
---
$FILENAME d

EOF
#git add $FILENAME
$EDITOR $FILENAME
