---
title: Blogolicious test blog!
description: just another blog
tmp_dir:  /path/to/blog/files/tmp
repo_dir: /path/to/blog/files/examples/blog

backends:
  post:
    module: file
    cfg:
      dir: posts/


# if you want to put it into production with hypnotoad, 2 x num_of_cores is good starting point
hypnotoad:
  workers: 8
