---
title: Blogolicious test blog!
description: just another blog
tmp_dir:  /path/to/blog/files/tmp
repo_dir: /path/to/blog/files/examples/blog
base_url: http://127.0.0.1:3000

default_layout: main

rss_item_count: 30

backends:
  post:
    module: file
    cfg:
      dir: posts/
  comments:
    module: file
    cfg:
      dir: comments/


# if you want to put it into production with hypnotoad, 2 x num_of_cores is good starting point
hypnotoad:
  workers: 8
